this.onYouTubeIframeAPIReady = function () {
  var movie, player;
  movie = youtube_url;
  $(".title").html(movie.title);
  return player = new YT.Player('player', {
    height: '390',
    width: '640',
    videoId: movie.id,
    events: {
      onReady: onPlayerReady,
      onStateChange: onPlayerStateChange,
      onError: onPlayerError
    }
  });
};

this.playNext = function (player) {
  var movie;
  player.clearVideo();
  movie = youtube_movie;
  $(".title").html(movie.title);
  player.loadVideoById(movie.id, 0, "large");
  return player.playVideo();
};

this.onPlayerReady = function (event) {
  return event.target.playVideo();
};

this.onPlayerStateChange = function (event) {
  if (event.data === YT.PlayerState.ENDED) {
    return playNext(event.target);
  }
};

this.onPlayerError = function (event) {
  return playNext(event.target);
};

// ---
// generated by coffee-script 1.9.2